spring:
  application:
    name: nacos-gateway
  cloud:
    sentinel:
      transport:
        # Sentinel流量监控中心地址
        dashboard: 192.168.1.108:9000
      eager: true
    gateway:
      enabled: true
      #route Id 转化小写
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        # 自定义的路由ID,保持唯一
        - id: nacos-consumer
          #目标服务地址
          uri: http://192.168.1.108:8080
          #路由条件
          predicates:
            #服务接口路径
            - Path=/dubbo/**
server:
  port: 9090