spring:
  application:
    name: nacos-consumer
  cloud:
    stream:
      bindings:
        source1:
          destination: test-topic-1
          group: group-1
          binder: rocketmq
        source2:
          destination: test-topic-2
          group: group-2
          binder: rocketmq
      rocketmq:
        binder:
          name-server:  http://192.168.1.108:9876
dubbo:
  protocol:
    id: dubbo
    name: dubbo
    port: -1
params:
  name: ""
  desc: ""


